Simple ftp
Sarapulov-Vas/Homework-3semester pull request #10
Opened 2024-10-14 20:56 UTC by Sarapulov-Vas

Solving the SimpleFTP Problem.

2024-12-25 11:26 UTC, yurii-litvinov requested changes

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/.editorconfig
> +dotnet_diagnostic.CS4014.severity = none
Это может быть ошибкой по делу, потому что если мы запускаем какую-то задачу, стоит хоть когда-то убедиться, что она закончилась

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/.editorconfig
> +dotnet_diagnostic.SA1010.severity = none
Это должно чиниться переходом на StyleCop 1.2 beta, который знает про современный C#

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/.editorconfig
> +dotnet_diagnostic.CS8602.severity = none
Это вообще грех выключать, это же ошибка типизации по сути

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +    private readonly int port = port;
Это по идее не нужно, параметры основного конструктора и так становятся полями

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +        var writer = new StreamWriter(stream);
Они вроде как тоже все IDisposable, стоило их с using писать

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +    public async Task<byte[]> Get(string path)
Лучше было принимать стрим, куда выводить скачанный файл, это позволило бы не держать его целиком в памяти (по крайней мере не обязательно — вызывающий мог бы подсунуть MemoryStream и получить такое же поведение, как у Вас). Но и так сойдёт, это можно не править.

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +    }
Надо бы либо тут дождаться завершения всех взаимодействий с клиентом, либо дать вызывающему это сделать, сделав Shutdown асинхронным (второй вариант предпочтительнее, потому что синхронный код при работе с сетью — прошлый век).

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                    var stream = new NetworkStream(socket);
Можно было тут `using (socket) { ... ` написать, тогда socket.Close бы точно вызвался

2024-12-25 11:26 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                throw new ArgumentException("Invalid request type.");
Я думаю, это не "грохнуть весь сервер из-за некорректного запроса", а "отправить ошибку клиенту" всё-таки :)

2024-12-26 09:46 UTC, ArtyomKopan approved these changes
10/10, не хватает только `using var socket = ...`

2025-02-15 15:42 UTC, merged